test: '{cipher}15ecb2d052fcc5d100c9e0cc7322b2e7f4ebfac744e9fcabb0ea34e06d86c26f'

server:
  port: 7011

spring:
  application:
    name: users-provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/ #,http://eureka2.com:6002/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  server:     
    port: 7011
  endpoints:
    web:
      exposure:
        include: "*"