test: cfgtest123

server:
  port: 7011

spring:
  application:
    name: users-provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/ #,http://eureka2.com:6002/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  server:     
    port: 7011
  endpoints:
    web:
      exposure:
        include: "*"