test: 666888
server:
  port: 9010
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:6001/eureka/

zuul:
  routes:
    usersprovider: /mprovider/*
    usersconsumer: /uconsumer/*
  ignored-patterns: /**/mymap/**