test: test1234
server:
  port: 9001

spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:6001/eureka/

zuul:
  routes:
    user-provider: /userprovider/**
    user-consumer: /userconsumer/**
  prefix: /gateway
  ignored-patterns: /**/mm/**

  #禁用某个过滤器
  AuthorityFilter:
    pre:
      disable: true
