test: test9999
server:
  port: 9001

spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的地址
    sender:
      type: web #请求方式,默认以http的方式向zipkin server发送追踪数据，其他取值如 kafka、rabbit
  sleuth:
    sampler:
      probability: 0.5 #采样的百分比,默认为0.1，即10%

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6001/eureka/

zuul:
  prefix: /gateway
  ignored-patterns: /**/cmap/**    		 #禁用某些路径
  routes:
    user-provider: /userprovider/**
    user-consumer: /userconsumer/**
  AuthorityFilter:
    pre:
      disable: true

  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000

