test: '{cipher}524106f191e6554340501cf01571a765ff2a084ddf311104b3a33a0f1ad7a65f'
server:
  port: 9002

spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@eureka1.com:6001/eureka/

zuul:
  routes:
    USERS-PROVIDER: /usersprovider/**	 #一个*只能匹配一层路径
    USERS-CONSUMER: /usersconsumer/**
  prefix: /gateway                       #前缀
  ignored-services: '*'                  #禁用服务名访问(内网不受该限制)
  ignored-patterns: /**/map/**          #禁用某些路径

