test: test123
server:
  port: 9001
spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6001/eureka/

zuul:
  routes:
    users-provider: /usersprovider/*
    users-consumer: /usersconsumer/*
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000

ribbon:
  ReadTimeout: 9000    #请求处理的超时时间
  SocketTimeout: 9000  #请求连接的超时时间
  ConnectTimeout: 9000