test: 1234
server:
  port: 9001

spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6001/eureka/

zuul:
  prefix: /gateway
  ignored-patterns: /**/cmap/**    		 #禁用某些路径
  routes:
    user-provider: /userprovider/**
    user-consumer: /userconsumer/**
  AuthorityFilter:
    pre:
      disable: true

  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000

