test: '{cipher}c865eca94c551ac53c235ba04023853aeb26b441d7b5de6d096528b5f5dcb42c'
server:
  port: 9002

spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:6001/eureka/

zuul:
  routes:
    user-provider: /userprovider/**
    user-consumer: /userconsumer/**
  prefix: /gateway
  ignored-patterns: /**/mm/**
  AuthorityFilter:
    pre:
      disable: true

  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000

