test: '{cipher}bce335d1b0db1e2d7dcc66b7b03b99cce4134ad5186bb3238a92ced97b07fbf7'
server:
  port: 9002
spring:
  application:
    name: gateway-zuul
  main:
    allow-bean-definition-overriding: true #允许多个服务引用网关

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:6001/eureka/

#网关路由
zuul:
  routes:
    users-provider: /userprovider/**     #一个*只能匹配一层路径
    users-consumer: /userconsumer/**     #rest风格必须写**
  prefix: /gateway
  ignored-services: '*'                  #禁用服务名访问(内网不受该限制)
  ignored-patterns: /**/mm/**

