test: 
  prod16666

server:
  port: 8004

spring:
  application:
    name: users-consumer
eureka:
  client:
    service-url:
      defaultZone: http://admin:123@eureka1.com:6001/eureka 
feign:
  hystrix:
    enabled: true


users-provider:
  ribbon:
    #NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
