test: 
  '{cipher}b775770d0824de9148d4a9f203d9da4eecba7a6793b4edf02b2717b9e7ec0ac4'

server:
  port: 8002

spring:
  application:
    name: users-consumer
eureka:
  client:
    service-url:
      defaultZone: http://admin:123@eureka1.com:6001/eureka 
feign:
  hystrix:
    enabled: true


users-provider:
  ribbon:
    #NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
